export {default as About} from './About/About'
export {default as Header} from './Header/Header'
export {default as Work} from './Work/Work'
export {default as Skills} from './Skills/Skills'
export {default as Footer} from './Footer/Footer'
export {default as Project01} from './Project01/Project01'
export {default as Project02} from './Project02/Project02'